version: '3'
services:
  mysql_node:
    container_name: petcare_database
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: 36562749
      MYSQL_DATABASE: petcare
      MYSQL_USER: aturing
      MYSQL_PASSWORD: 36562749
    restart: on-failure
    ports:
      - 3306:3306
    networks:
      petcare:
        ipv4_address: 192.168.7.2

  server_node:
    container_name: petcare_api   
    build: 
      context: ../
      dockerfile: ./Docker/api/Dockerfile
    ports:
      - 5039:5039
      - 6789:6789
    depends_on:
      - mysql_node
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      petcare:
        ipv4_address: 192.168.7.3
    restart: on-failure

networks:
  petcare:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.7.0/24
